name: TwitchLiveAnnouncer
version: '${version}'
main: it.ax3lt.tla.TwitchLiveAnnouncerPlugin
author: ax3lt
description: A simple plugin to notify when a streamer goes live
depend: [ PlaceholderAPI ]
commands:
  stream:
    aliases:
      - twitch
      - tla
    description: Stream command
    usage: /stream <reload> <add> <remove>
    permission-message: You don't have permission to use this command
    default: op
    tabcomplete: [ reload ]
  setchannel:
    description: Set your twitch channel
    usage: /setchannel <channel>
    permission: twitchliveannouncer.setchannel
    default: true
  clearchannel:
    description: Clear your twitch channel
    usage: /clearchannel
    permission: twitchliveannouncer.clearchannel
    default: true

permissions:
  twitchliveannouncer.reload:
    description: Reload the config
    default: op
  twitchliveannouncer.forceCheck:
    description: Force live check for all channels
    default: op
  twitchliveannouncer.link.add:
    description: Add a linked user (minecraft -> twitch)
    default: op
  twitchliveannouncer.link.remove:
    description: Remove a linked user (minecraft -> twitch)
    default: op
  twitchliveannouncer.link.list:
    description: List all linked users
    default: op
  twitchliveannouncer.link.multiple:
    description: Link multiple channels to a player
    default: op
  twitchliveannouncer.channels.add:
    description: Add a channel to the list of channels to check
    default: op
  twitchliveannouncer.channels.remove:
    description: Remove a channel from the list of channels to check
    default: op
  twitchliveannouncer.channels.list:
    description: List all channels to check
    default: op